apiVersion: kustomize.config.k8s.io/v1beta1
bases:
- components/111/base
- components/demo1/base
- components/nodejs-sample/base
- components/nodejs/base
kind: Kustomization
resources:
- common-storage-pvc.yaml
