apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: "111"
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: "111"
    app.kubernetes.io/part-of: purple-mermaid-app
  name: "111"
  namespace: rorai
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: "111"
status:
  loadBalancer: {}
